# Generated by Django 6.1 on 2026-09-07 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Раздел",
                "verbose_name_plural": "Разделы",
            },
        ),
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.CreateModel(
            name="Scope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Основной"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scopes",
                        to="articles.article",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scopes",
                        to="articles.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Раздел статьи",
                "verbose_name_plural": "Разделы статьи",
                "ordering": ["-is_main", "tag__name"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                related_name="articles", through="articles.Scope", to="articles.tag"
            ),
        ),
    ]
