# Generated by Django 6.1 on 2026-08-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("image", models.CharField(max_length=200)),
                ("release_date", models.DateField()),
                ("lte_exists", models.BooleanField()),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
